package componentetimer;

import componentetimer.gui.TemporizadorComponent;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * Método para probar el componente temporizador creado
 * @author Juan José Vidal Hernández
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private TemporizadorComponent temporizadorEjercicio;
    private TemporizadorComponent temporizadorDescanso;

    /**
     * Constructor
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMinutosEjercicio = new javax.swing.JLabel();
        jLabelMinutosDescanso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMinutosEjercicio = new javax.swing.JTextField();
        jTextFieldSegundosEjercicio = new javax.swing.JTextField();
        jTextFieldMinutosDescanso = new javax.swing.JTextField();
        jLabelSegundosDescanso = new javax.swing.JLabel();
        jLabelTiempoEjercicio = new javax.swing.JLabel();
        jLabelTiempoDescanso = new javax.swing.JLabel();
        jTextFieldSegundosDescanso = new javax.swing.JTextField();
        jCheckBoxSonidoInicio = new javax.swing.JCheckBox();
        jCheckBoxSonidoFin = new javax.swing.JCheckBox();
        jButtonComenzar = new javax.swing.JButton();
        jLabelSeries = new javax.swing.JLabel();
        jTextFieldSeries = new javax.swing.JTextField();
        jPanelTemporizadores = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMinutosEjercicio.setText("Min");

        jLabelMinutosDescanso.setText("Min");

        jLabel3.setText("Seg");

        jTextFieldMinutosEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMinutosEjercicioActionPerformed(evt);
            }
        });

        jLabelSegundosDescanso.setText("Seg");

        jLabelTiempoEjercicio.setText("Tiempo de ejercicio");

        jLabelTiempoDescanso.setText("Tiempo de descanso");

        jCheckBoxSonidoInicio.setText("Sonido inicio");

        jCheckBoxSonidoFin.setText("Sonido fin");

        jButtonComenzar.setText("¡Comenzar!");
        jButtonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComenzarActionPerformed(evt);
            }
        });

        jLabelSeries.setText("Series");

        javax.swing.GroupLayout jPanelTemporizadoresLayout = new javax.swing.GroupLayout(jPanelTemporizadores);
        jPanelTemporizadores.setLayout(jPanelTemporizadoresLayout);
        jPanelTemporizadoresLayout.setHorizontalGroup(
            jPanelTemporizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        jPanelTemporizadoresLayout.setVerticalGroup(
            jPanelTemporizadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSeries)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMinutosEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMinutosEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMinutosDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMinutosDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBoxSonidoFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxSonidoInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSegundosEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTiempoEjercicio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSegundosDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSegundosDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelTiempoDescanso)))))
                .addGap(81, 81, 81)
                .addComponent(jPanelTemporizadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldSegundosEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTiempoEjercicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSegundosDescanso)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelTiempoDescanso)
                                .addComponent(jTextFieldSegundosDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMinutosEjercicio)
                            .addComponent(jTextFieldMinutosEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMinutosDescanso)
                            .addComponent(jTextFieldMinutosDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSeries)
                    .addComponent(jTextFieldSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxSonidoInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSonidoFin)
                .addGap(18, 18, 18)
                .addComponent(jButtonComenzar)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTemporizadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMinutosEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMinutosEjercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMinutosEjercicioActionPerformed

    private void jButtonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarActionPerformed
        try {
            String minutosEjercicio = jTextFieldMinutosEjercicio.getText();
            String segundosEjercicio = jTextFieldSegundosEjercicio.getText();
            String minutosDescanso = jTextFieldMinutosDescanso.getText();
            String segundosDescanso = jTextFieldSegundosDescanso.getText();
            String series = jTextFieldSeries.getText();
            boolean sonidoInicio = jCheckBoxSonidoInicio.isSelected();
            boolean sonidoFin = jCheckBoxSonidoFin.isSelected();

            SwingUtilities.invokeLater(() -> {
                temporizadorEjercicio = new TemporizadorComponent(minutosEjercicio, segundosEjercicio, sonidoInicio, sonidoFin);
                temporizadorDescanso = new TemporizadorComponent(minutosDescanso, segundosDescanso, sonidoInicio, sonidoFin);
                JFrame frame = new JFrame("TemporizadorComponent");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(400, 200);

                JButton startButton = new JButton("Iniciar Temporizador");
                startButton.addActionListener(e -> {
                    try {
                        temporizadorEjercicio.iniciarCuentaAtras(minutosEjercicio, segundosEjercicio, sonidoInicio, series);
                        temporizadorDescanso.iniciarCuentaAtras(minutosDescanso, segundosDescanso, sonidoInicio, series);
                    } catch (IllegalArgumentException ex) {
                        JOptionPane.showMessageDialog(frame, ex.getMessage());
                    }
                });

                // Configura un GridLayout para organizar temporalmente los componentes en dos filas y una columna
                JPanel tempPanel = new JPanel(new GridLayout(2, 1));
                tempPanel.add(temporizadorEjercicio);
                tempPanel.add(temporizadorDescanso);

                // Configura el diseño de la frame con un BorderLayout
                frame.setLayout(new BorderLayout());
                frame.add(tempPanel, BorderLayout.CENTER);
                frame.add(startButton, BorderLayout.SOUTH);  // Agrega el botón en la parte inferior

                frame.setVisible(true);
            });
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Sólo carácteres númericos permitidos.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingrese números enteros válidos. Entre 0 y 60 para segundos y minutos. Y entre 1 y 20 para series");
        }
    }//GEN-LAST:event_jButtonComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComenzar;
    private javax.swing.JCheckBox jCheckBoxSonidoFin;
    private javax.swing.JCheckBox jCheckBoxSonidoInicio;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMinutosDescanso;
    private javax.swing.JLabel jLabelMinutosEjercicio;
    private javax.swing.JLabel jLabelSegundosDescanso;
    private javax.swing.JLabel jLabelSeries;
    private javax.swing.JLabel jLabelTiempoDescanso;
    private javax.swing.JLabel jLabelTiempoEjercicio;
    private javax.swing.JPanel jPanelTemporizadores;
    private javax.swing.JTextField jTextFieldMinutosDescanso;
    private javax.swing.JTextField jTextFieldMinutosEjercicio;
    private javax.swing.JTextField jTextFieldSegundosDescanso;
    private javax.swing.JTextField jTextFieldSegundosEjercicio;
    private javax.swing.JTextField jTextFieldSeries;
    // End of variables declaration//GEN-END:variables
}
